name: D8 Code Review

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  phpcs-drupal:
    name: Drupal coding standards
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: guix77/phpcs-drupal-action@v1.0.1
